apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  micro2
  template:
    metadata:
      labels:
        app:  micro2
    spec:
      containers:
      - image: deepakjotwani/simplr-frontend
        name:  micro2
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
---

  apiVersion: v1
  kind: Service
  metadata:
    name: micro2-service
    annotations:
  spec:
    ports:
    - port: 9090
      targetPort: 5000
    selector:
      app: micro2
    type: LoadBalancer
    