---
_extends: .github  
repository:
  descritpion: test
  topics: test
  private: false
teams:
  - name: persistent
    permission: admin
branches:
  - name: develop
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
      
