---
_extends: .github
repository:
  default_branch: develop
  descritpion: Test
  private: false
  has_projects: false
branches:
  - name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismis_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts: []
      restrictions: null
