---
_extends: .github
repository:
  default_branch: master
  descritpion: Service that stores/manages the generic asset data discovered from customer cloud environments (AWS, Azure etc.).
  private: true
  has_projects: false
teams:
  - name: persistent
    permission: push
branches:
  - name: master
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismis_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      restrictions: null
