---
_extends: .github
repository:
  descritpion: test
  topics: test
  private: false
teams:
  - name: persistent
    permission: push
branches:  
  - name: develop
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismis_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
        dismissal_restrictions:
          teams: [persistent-leads]
      required_status_checks:
        strict: true
        contexts: []
      restrictions:
        teams: [persistent-leads]
