---
repository:
  default_branch: master
  description: Test
  private: false
  has_projects: false
  has_wiki: false

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
  - name: develop 
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
