---
_extends: .github  
repository:
  descritpion: test
  topics: test
  private: false
teams:
  - name: persistent
    permission: admin
branches:
  - name: develop
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismis_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 5
        dismissal_restrictions:
          teams: []
          users: []
      required_status_checks:
        strict: true
        contexts: []
      restrictions:
        teams: []
        users: []
      
