---
repository:
  description: Test
  topics: test
  private: false
  has_projects: false
  has_wiki: false

branches:
  - name: develop 
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismis_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
        dismissal_restrictions:
          teams: []
          users: []
      required_status_checks:
        strict: true
        context: []
      restrictions:
        teams: []
        users: []
      
