---
_extends: .github  
repository:
  descritpion: test
  topics: test
  private: false
teams:
  - name: persistent
    permission: push
branches:
  - name: develop
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismis_stale_reviews: true
        require_code_owner_reviews: false
        required_approving_review_count: 3
      required_status_checks: null
      restrictions: null
      
