---
_extends: .github
repository:
  default_branch: master
  descritpion: Test
  private: false
  has_projects: false
branches:
  - name: "feature/*"
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismis_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts: []
      restrictions: null
