apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-mgmt-frontend-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepakjotwani/argo-poc.git
    targetRevision: HEAD
    path: argo/dev/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false