apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro1
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/deepakjotwani/argo-poc.git 
    targetRevision: HEAD
    path: microservice1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true