apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
      argocd-image-updater.argoproj.io/image-list: micro1=deepakjotwani/sample2
      argocd-image-updater.argoproj.io/micro1.update-strategy: latest
      argocd-image-updater.argoproj.io/micro1.kustomize.image-name: deepakjotwani/sample2
  name: micro1
  namespace: argocd
spec:
  destination:
    namespace: default  
    server: https://kubernetes.default.svc
  project: default
  source:
    path: microservice1/micro1
    repoURL: https://github.com/deepakjotwani/argo-poc.git 
    targetRevision: HEAD
