apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro1
spec:
  destination:
    namespace: default  
    server: https://kubernetes.default.svc
  project: default
  source:
    path: microservice1/micro1
    repoURL: https://github.com/deepakjotwani/argo-poc.git 
    targetRevision: HEAD