apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  micro1
  template:
    metadata:
      labels:
        app:  micro1
    spec:
      containers:
      - image: deepakjotwani/simplr-frontend
        name:  micro1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
---

  apiVersion: v1
  kind: Service
  metadata:
    name: micro1-service
    annotations:
  spec:
    ports:
    - port: 8080
      targetPort: 5000
    selector:
      app:  micro1
    type: LoadBalancer
    
