apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  micro1
  template:
    metadata:
      labels:
        app:  micro1
    spec:
      containers:
      - image: micro1-image
        name:  micro1
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
---

  apiVersion: v1
  kind: Service
  metadata:
    name: micro1-service
    annotations:
  spec:
    ports:
    - port: 80
      targetPort: 8080
    selector:
      app:  micro1
    type: LoadBalancer
    
