---
name: Application CI Pipeline on Push
env:
  ARTIFACTORY_BUCKET: eng-docker-qa-local
  ARTIFACTORY: beyondtrust-$ARTIFACTORY_BUCKET.jfrog.io
  CONTAINER_IMAGE: $ARTIFACTORY/svc-discovery-develop
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ env.CONTAINER_IMAGE }}
